### ISSUE TITLE
[Feature] Make YAML wildcard support "k: v" pairs

### ISSUE THREAD

**Issue by PurplefinNeptuna** [ltdrdata/ComfyUI-Impact-Pack#642]
Currently this is not supported.
sorry for dirty examples:
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/23467102/7ade8b89-9659-43c7-bbb8-830b413dd420)
I usually use them like `__boob/*/*__`

**Comment by ltdrdata** [comment]
What is the meaning of that?

**Comment by PurplefinNeptuna** [comment]
currently the wildcard only accepting dictionary values as list or dictionary, not a string
example:
```yaml
# Key contain a list is working
A:
  - B
  - C

# Key contain dict is also working
A:
  B:
    - C
  D:
    - E

# But if the key's value is a string, it doesn't work
A: B

# This also doesn't work
A:
  B: C

# Both example above are valid YAML, but not working as wildcard YAML
```
