### ISSUE TITLE
Possible `UltralyticsDetectorProvider` & `SAMLoader` bug: inconsistent handling of non-default `base_path` between install and runtime

### ISSUE THREAD

**Issue by mbac** [ltdrdata/ComfyUI-Impact-Pack#828]
Hi!

I think I caught a bug in the way at least `UltralyticsDetectorProvider` and `SAMLoader`.

I'm using the following options in `extra_model_paths.yaml`:
```
comfyui:
     base_path: /workspace/models
     # You can use is_default to mark that these folders should be listed first, and used as the default dirs for eg downloads
     is_default: true
     checkpoints: checkpoints/
     clip: clip/
     clip_vision: clip_vision/
     configs: configs/
     controlnet: controlnet/
     diffusion_models: |
                  diffusion_models
                  unet
     embeddings: embeddings/
     loras: loras/
     upscale_models: upscale_models/
     vae: vae/
     ultralytics: ultralytics/
```
This seems to work with 99% nodes I'm using, which have no trouble finding models. When installing Impact Pack, the installer script correctly downloads YOLO files to `/models/ultralytics/bbox` & `segm/` (i.e., to a folder outside `ComfyUI/`).

However, the nodes will **not** see the models unless they are moved (or linked) into `ComfyUI/models/ultralytics...` despite the yaml file settings.

Linking the directories (e.g. in my case `ln -s /workspace/models/ultralytics /workspace/ComfyUI/models/`) works around the problem but I wonder if this can be fixed at the node level… unless of course I've got the yaml syntax all wrong 😏

Thanks!
